version: "3.8"
services:
  db:
    image: postgres
    container_name: nex-pro-biz-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nex-pro-biz-db
      POSTGRES_PASSWORD: nex-pro-biz-password
      POSTGRES_DB: nex-pro-biz
    volumes:
      - nex-pro-biz-db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: nex-pro-biz-pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: yumnaahware@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nex-pro-biz-password
    volumes:
      - nex-pro-biz-pgadmin-data:/var/lib/pgadmin

volumes:
  nex-pro-biz-db-data:
  nex-pro-biz-pgadmin-data:
