import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import ThemeRegistry from "@/providers/ThemeRegistry";
import CookieConsent from "@/components/layout/CookieConsent";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const consent = cookieStore.get("cookie_consent")?.value === "true";
  const themeCookie = cookieStore.get("theme")?.value;
  const initialDark = consent && themeCookie === "dark";
  return (
    <html lang="en" className={initialDark ? "dark" : undefined}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeRegistry>
          <ThemeProvider>
            {children}
            <CookieConsent />
          </ThemeProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
